#!/bin/bash

items() {
  while test -n "$1"; do
    if test -f "$CONFIG_DIR/items/$1.sh"; then
      source "$CONFIG_DIR/items/$1.sh"
    fi
    shift
  done
}

sketchybar --bar position=top height=30 notch_display_height=33 blur_radius=30 color=0x40000000 padding_left=0

default=(
  padding_left=0
  padding_right=0
  icon.font="SF Pro:Semibold:14.0"
  label.font="SF Pro:Semibold:13.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

## Left Items
items apple

# items switcher
# switcher aerospace menubar

items aerospace
# items menubar

## Right Items
items clock
items controlcenter
# items more
items network
items cpu
items battery
items weather
items timemachine
items trash
items app_badge
items events

sketchybar --hotload true
sketchybar --update
