#!/bin/bash
DOTFILES_NAME=.dotfiles

# Shortcuts
alias reloaddns="dscacheutil -flushcache && sudo killall -HUP mDNSResponder"
alias reloadzshplugins="rm -f ~/.zsh_plugins ~/.zsh_plugins.tmux && source ~/.zshrc"

alias dr="defaults read"
alias dw="defaults write"

# exa (ls replacement)
alias ls="exa"
alias l="exa -lFh --git"
alias la="exa -laFh --git"
alias ll="exa -l --git"

# news
alias news="curl -sSL hackurls.com/ascii | less"

# HTTPie
alias https="http --default-scheme=https"

# Docker
alias d='docker'

# Test if docker is running or not
docker info >/dev/null 2>&1
if [ $? -eq 0 ]; then
  # Docker is running, setting aliases to use Docker instead
  if [ "$(arch)" = "armv7l" ]; then
    # Raspberry Pi variant
    alias mysql="docker run -it --rm --name mysql-cli jsurf/rpi-mariadb mysql"
  else
    alias mysql="docker run -it --rm --name mysql-cli mysql:5.7 mysql"
  fi

  alias node="docker run -it --rm --name node-cli -v \$(pwd):/opt/app -w /opt/app node:lts-alpine node"
  alias npm="docker run -it --rm --name npm-cli -v \$(pwd):/opt/app -w /opt/app node:lts-alpine npm"
  alias python2="docker run -it --rm --name python2-cli -v \$(pwd):/opt/app -w /opt/app python:2-alpine python"
  alias python3="docker run -it --rm --name python3-cli -v \$(pwd):/opt/app -w /opt/app python:3-alpine python"
  alias terraform="docker run -it --rm --name terraform-cli -v \$(pwd):/opt/app -w /opt/app hashicorp/terraform"
  alias build-wtfutil="curl -sSL https://raw.githubusercontent.com/wtfutil/wtf/master/Dockerfile | docker build --build-arg=version=v0.26.0 -t wtfutil -"
  alias wtfutil="docker run -it --rm --name wtfutil -v ${HOME}/$DOTFILES_NAME/wtfutil/config.yml:/config/config.yml wtfutil --config=/config/config.yml"
  alias browsh="docker run --rm -it browsh/browsh"

  # Docker version of tools
  alias docker-redis="docker run -d -p 6379:6379 --rm --name redis redis:alpine"
  alias docker-mongo="docker run -d -p 27017:27017 --rm --name mongo mongo"
  alias docker-mysql="docker run -d -p 3306:3306 --rm -e MYSQL_ROOT_PASSWORD=root -v ${HOME}/mysql/data:/var/lib/mysql -v ${HOME}/$DOTFILES_NAME/mysql/config:/etc/mysql/conf.d --name mysql mysql:5.7"
fi

unalias vol >/dev/null 2>/dev/null
if [ "$(uname)" = "Darwin" ]; then
  vol() {
    osascript -e "set Volume $((($1 + 5) / 10))"
  } 
else
  alias vol="amixer set Master"
fi

# TMUX
alias tmux="tmux -2"

# NVIM
alias vim="nvim"
alias vi="nvim"

# lazygit
alias lg="lazygit"

# HSTR configuration - add this to ~/.zshrc
alias hh=hstr                    # hh to be alias for hstr
setopt histignorespace           # skip cmds w/ leading space from history
export HSTR_CONFIG=hicolor       # get more colors
export SAVEHIST=100000
bindkey -s "\C-r" "\eqhstr\n"     # bind hstr to Ctrl-r (for Vi mode check doc)

# for opt + ← and opt + → to skip a word
bindkey '^[[1;3C' forward-word
bindkey '^[[1;3D' backward-word
