#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child

yabai -m config window_topmost               off
yabai -m config window_opacity               off

yabai -m config window_shadow                float
yabai -m config window_border                on

yabai -m config active_window_border_color   0xff8E83B8
yabai -m config normal_window_border_color   0xff51425C
yabai -m config insert_window_border_color   0xff8E83B8
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  26
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   5

yabai -m rule --add app=Slack space=1 display=2
yabai -m rule --add app="^Mail$|^Spark$" space=2 display=1
yabai -m rile --add app="Term" space=3 display=1
yabai -m rule --add app="Chrome|Safari" title="Jira" space=4 display=2
yabai -m rule --add app="Chrome|Safari" title="New Relic" space=4 display=3
yabai -m rule --add app="TablePlus|MySQL|Sequel" space=5 display=1
yabai -m rule --add app="^Finder$" space=6 display=1

yabai -m rule --add app="^Finder$" title="Co(py|nnect)|Move|Info|Pref" manage=off
yabai -m rule --add app="^App Store$"
yabai -m rule --add app="^System Preferences$" mange=off

