#!/bin/bash
DOTFILES_NAME=.dots

# Ctrl+Z will send the process to background, use "resume" to bring it back
alias resume="fg"

# git
alias glgfp="glg --first-parent"
alias glggfp="glgg --first-parent"

# git revert
alias grevc="grev --continue"
alias greva="grev --abort"
alias grevs="grev --skip"

# git worktree
alias gwt="git worktree"
alias gwta="git worktree add"
alias gwtl="git worktree list"
alias gwtm="git worktree move"
alias gwtp="git worktree prune"
alias gwtrm="git worktree remove"
# kill the annoyance
alias ga.="ga ."

# Shortcuts
alias reloaddns="dscacheutil -flushcache && sudo killall -HUP mDNSResponder"

alias dr="defaults read"
alias dw="defaults write"

# exa (ls replacement)
alias ls="exa"
alias l="exa -lFh"
alias la="exa -laFh"
alias ll="exa -l"

# bat (cat replacement)
if test -n "$(command -v bat)"; then
  alias cat="bat"
elif test -n "$(command -v batcat)"; then
  alias cat="batcat"
fi

alias news="curl -sSL hackurls.com/ascii | less"
alias reddit="ssh redditbox.us"

# unicode test
alias utf8demo="curl -sSL https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt"
alias quickbrown="curl -sSL https://www.cl.cam.ac.uk/~mgk25/ucs/examples/quickbrown.txt"

# termbin (pipe text to this alias)
alias tb="nc termbin.com 9999"

# show public ip
if test -n "$(command -v curl)"; then
  alias myip="curl eth0.me"
elif test -n "$(command -v nc)"; then
  alias myip="echo GET / | nc eth0.me 80"
else
  myip() {
    echo "Error: 'curl' or 'nc' is not installed. Try browsing eth0.me manully."
  }
fi

# function aliases
alias search_prs=search_github
alias search_issues=search_github

# Docker
alias d="$(command -v docker)"

# Podman
alias p="podman"
alias docker="podman"

# github cli - issues
alias iscl="gh issue close"
alias isc="gh issue create"
alias isl="gh issue list"
alias isr="gh issue reopen"
alias iss="gh issue status"
alias isv="gh issue view"

# github cli - pull requests
alias pra="gh pr checks"
alias prc="gh pr create"
alias prch="gh pr checks"
alias prcl="gh pr close"
alias prco="gh pr checkout"
alias prd="gh pr diff"
alias prl="gh pr list"
alias prm="gh pr merge"
alias prr="gh pr review"
alias prs="gh pr status"
alias prv="gh pr view"

# github cli - custom commands
alias prcm="tkcm"
alias iscm="tkcm"

unalias vol >/dev/null 2>/dev/null
if test "$(uname)" = "Darwin"; then
  vol() {
    osascript -e "set Volume $(( ($1 + 5) / 10 ))"
  }
else
  alias vol="amixer set Master"
fi

# tmux
alias tmux="tmux -2"

# nvim
alias vi="nvim"
alias vim="nvim"
alias vi-profile="nvim-profile"
alias vim-profile="nvim-profile"
alias nvim-profile="nvim --startuptime vim.log -c 'qa!' && cat vim.log && rm -f vim.log"

# lazygit
alias lg="lazygit"

# for opt + ← and opt + → to skip a word
bindkey '^[[1;3C' forward-word
bindkey '^[[1;3D' backward-word
