#!/bin/zsh
# Ctrl+Z will send the process to background, use "resume" to bring it back
alias resume="fg"

# quick project switching
alias w=". work"
alias c=". navigate"

# git
alias gaap="gaa --patch"
alias glgfp="glg --first-parent"
alias glggfp="glgg --first-parent"

alias gig="git ignore"
alias glig="git local-ignore"

# git revert
alias grevc="grev --continue"
alias greva="grev --abort"
alias grevs="grev --skip"

# git stash
alias gstas="gsta --staged"

# git worktree
unalias gwt >/dev/null 2>/dev/null
gwt() {
  if test -z "$1"; then
    git worktree list
    return
  fi
  case "$1" in
    a)
      shift
      git worktree add "$@"
      ;;
    ls)
      shift
      git worktree list "$@"
      ;;
    mv)
      shift
      git worktree move "$@"
      ;;
    rm)
      shift
      git worktree remove "$@"
      ;;
    *)
      git worktree "$@"
      ;;
  esac
}

# kill the annoyance
alias ga.="ga ."

# jujutsu
alias j="jj"
alias jc="jj commit"
alias jcm="jj commit --message"
alias jd="jj diff"
alias jds="jj desc"
alias jdm="jj desc --message"
alias je="jj edit"
alias jcl="jj git clone"
alias jf="jj git fetch"
alias jfa="jj git fetch --all-remotes"
alias jp="jj git push"
alias jl="jj log"
alias jla="jj log -r '::'"
alias jlg="jj log -r '::@'"
alias jn="jj new"
alias jrb="jj rebase"
alias jrs="jj restore"
alias jsp="jj split"
alias jsq="jj squash"
alias jst="jj status"
alias jsh="jj show"
alias ju="jj undo"
alias jr="jj redo"

# Shortcuts
alias reloaddns="dscacheutil -flushcache && sudo killall -HUP mDNSResponder"

alias dr="defaults read"
alias dw="defaults write"

# exa (ls replacement)
if test -n "$(command -v eza)"; then
  alias ls="eza"
  alias l="eza -lhF"
  alias la="eza -lahF"
  alias ll="eza -l"
elif test -n "$(command -v exa)"; then
  alias ls="exa"
  alias l="exa -lhF"
  alias la="exa -lahF"
  alias ll="exa -l"
fi

# bat (cat replacement)
if test -n "$(command -v bat)"; then
  alias cat="bat"
elif test -n "$(command -v batcat)"; then
  alias cat="batcat"
fi

alias news="curl -sSL hackurls.com/ascii | less"
alias reddit="ssh redditbox.us"

# unicode test
alias utf8demo="curl -sSL https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt"
alias quickbrown="curl -sSL https://www.cl.cam.ac.uk/~mgk25/ucs/examples/quickbrown.txt"

# termbin (pipe text to this alias)
alias tb="nc termbin.com 9999"

# show public ip
if test -n "$(command -v curl)"; then
  alias myip="curl eth0.me"
elif test -n "$(command -v nc)"; then
  alias myip="echo GET / | nc eth0.me 80"
else
  myip() {
    echo "Error: 'curl' or 'nc' is not installed. Try browsing eth0.me manully."
  }
fi

# function aliases
alias search_prs=search_github
alias search_issues=search_github

# Container Engine
alias p="podman"
alias d="docker"

# github cli - issues
alias iscl="gh issue close"
alias isc="gh issue create"
alias isl="gh issue list"
alias isr="gh issue reopen"
alias iss="gh issue status"
alias isv="gh issue view"

# github cli - pull requests
alias pra="gh pr checks"
alias prc="gh pr create"
alias prch="gh pr checks"
alias prcl="gh pr close"
alias prco="gh pr checkout"
alias prd="gh pr diff"
alias prl="gh pr list"
alias prm="gh pr merge"
alias prr="gh pr review"
alias prs="gh pr status"
alias prv="gh pr view"

# github cli - custom commands
alias prcm="tkcm"
alias iscm="tkcm"

unalias vol >/dev/null 2>/dev/null
if test "$(uname)" = "Darwin"; then
  vol() {
    osascript -e "set Volume $(( ($1 + 5) / 10 ))"
  }
else
  alias vol="amixer set Master"
fi

# tmux
alias tmux="tmux -2"

# nvim
alias vi="nvim"
alias vim="nvim"
alias vi-profile="nvim-profile"
alias vim-profile="nvim-profile"
alias nvim-profile="nvim --startuptime vim.log -c 'qa!' && cat vim.log && rm -f vim.log"

# lazygit
alias lg="lazygit"

# for opt + ← and opt + → to skip a word
bindkey '^[[1;3C' forward-word
bindkey '^[[1;3D' backward-word
