#!/bin/bash
DOTFILES_NAME=.dots

export EDITOR=nvim

# increase history size
export HISTFILE=~/.zsh_history
export HISTSIZE=1000000
export SAVEHIST=100000

# better word separator
export WORDCHARS='~!#$%^&*(){}[]<>?.+;-'

# use ripgrep by default for fzf
export FZF_DEFAULT_COMMAND='rg --files --hidden'

# zsh-you-should-use
export YSU_MESSAGE_POSITION="after"
export YSU_IGNORED_ALIASES=("g" "ga." "d" "p" "vi" "vim" "search_prs" "search_issues" "bi" "bu" "bup")

# use bat as a man pager
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# export binaries to path
export PATH="$HOME/$DOTFILES_NAME/binaries:$PATH"

# setup locales, to fix...
# - https://github.com/jwilm/alacritty/issues/2566
# - https://github.com/neovim/neovim/issues/5683
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

export HOMEBREW_USE_INTERNAL_API=1
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_ENV_HINTS=1
export NOW_PLAYING_SHADA="$HOME/.cache/now-playing"

# suppress warnings (especially on git)
export STARSHIP_LOG=error

if test -z "$TERM_APP"; then
  export TERM_APP="$TERM_PROGRAM"
fi
