#!/bin/bash

# set dotnet root and its binary to have it running properly
if test -n "$(command -v asdf)" && asdf current dotnet-core 1>/dev/null 2>&1; then
  export DOTNET_ROOT="$(asdf where dotnet-core)"

  if test -d "$HOME/.dotnet/tools"; then
    export PATH="$HOME/.dotnet/tools:$PATH"
  fi

  export PATH="$DOTNET_ROOT:$PATH"
fi

if test -n "$(command -v asdf)"; then
  export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
fi

# clangd (through llvm if installed)
if test -d /usr/local/opt/llvm/bin; then
  export PATH="/usr/local/opt/llvm/bin:$PATH"
fi

if test -n "$(command -v shrimp)"; then
  export PATH=$PATH:$HOME/.shrimp/bin
fi

if test -d "$HOME/Library/Application Support/Coursier/bin"; then
  export PATH="$PATH:$HOME/Library/Application Support/Coursier/bin"
fi

if test -d "/opt/homebrew/opt/jq/bin"; then
  export PATH="/opt/homebrew/opt/jq/bin:$PATH"
fi

if test -d "/opt/homebrew/opt/ruby/bin"; then
  export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
fi

# Use homebrew version for security key support
if test -d "/opt/homebrew/opt/openssh/bin"; then
  export PATH="/opt/homebrew/opt/openssh/bin:$PATH"
  export GIT_SSH="/opt/homebrew/opt/openssh/bin/ssh"
fi
