#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[revsets]
bookmark-advance-to = "closest_pushable(@)"

[revset-aliases]
'closest_pushable(to)' = '''
  heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))
'''

[user.me]
name = "Sirisak Lueangsaksri"
email = "1087399+spywhere@users.noreply.github.com"

[aliases]
d = ["diff"]
clone = ["git", "clone"]
identity = ["util", "exec", "--", "bash", "-c", """
  if test -z "$1"; then
    echo "usage: jj identity <identity>"
    echo
    echo "available identities:"
    jj config list -T 'name++"\n"' user | grep 'user\\..*\\.name' | cut -d. -f2 | sed 's/^/  - /'
    exit 0
  fi

  name="$(jj config get user.$1.name)" || exit
  email="$(jj config get user.$1.email)" || exit

  JJ_USER="$name" JJ_EMAIL="$email" jj metaedit --update-author || exit
  jj config set --repo user.name "$name"
  jj config set --repo user.email "$email"
""", ""]

[ui]
default-command = "help"
