#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[templates]
log = "tidy_log"

# Check jcf list --include-defaults
[template-aliases]
tidy_log = """
  if(self.root(),
    format_root_commit(self),
    label(
      separate(" ",
        if(self.current_working_copy(), "working_copy"),
        if(self.immutable(), "immutable", "mutable"),
        if(self.conflict(), "conflicted"),
      ),
      separate(" ",
        pad_end(
          4,
          separate("/",
            self.change_id().shortest(4),
            if(self.divergent() || self.hidden(), self.change_offset()),
          )
        ),
        separate("",
          if(self.conflict(), label("error heading", "!"), " "),
          if(self.immutable(), label("warning heading", "i"), " "),
          if(self.empty(), label("hint heading", "e"), " "),
        ),
        self.bookmarks(),
        self.tags(),
        self.working_copies(),
        if(self.description(),
          if(is_conventional_commit(self.description().first_line()),
            format_conventional_commit(self.description().first_line()),
            self.description().first_line().substr(0, 80),
          ),
          label(if(self.empty(), "empty"), description_placeholder),
        ),
        commit_timestamp(self).local().format("%y%m%d%H%M%S"),
        self.author().email().local(),
      ) ++ "\n",
    ),
  )
"""
"is_conventional_commit(desc)" = """
  desc.match(regex:"[a-z0-9_-]+!?([(][a-z0-9_-]+[)])?:")
"""
"format_conventional_commit(desc)" = """
  concat(
    label("commit_id", desc.split(":", 2).first() ++ ":"),
    desc.split(":", 2).last(),
  )
"""

[remotes.origin]
auto-track-created-bookmarks = "*"

[revsets]
bookmark-advance-to = "closest_pushable(@)"

[revset-aliases]
'closest_pushable(to)' = '''
  heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))
'''

[user.me]
name = "Sirisak Lueangsaksri"
email = "1087399+spywhere@users.noreply.github.com"

[aliases]
d = ["diff"]
clone = ["git", "clone"]
identity = ["util", "exec", "--", "bash", "-c", """
  if test -z "$1"; then
    echo "usage: jj identity <identity>"
    echo
    echo "available identities:"
    jj config list -T 'name++"\n"' user | grep 'user\\..*\\.name' | cut -d. -f2 | sed 's/^/  - /'
    exit 0
  fi

  name="$(jj config get user.$1.name)" || exit
  email="$(jj config get user.$1.email)" || exit

  JJ_USER="$name" JJ_EMAIL="$email" jj metaedit --update-author || exit
  jj config set --repo user.name "$name"
  jj config set --repo user.email "$email"
""", ""]

[ui]
default-command = "status"
diff-formatter = "delta"
