#!/bin/sh

# brew and fzf
# update multiple packages at once
# mnemonic [B]rew [U]pdate [P]lugin

__inst=$(brew search | eval "fzf ${FZF_DEFAULT_OPTS} -m --header='[brew:install]'")

if test -n "$__inst"; then
  for __prog in $__inst; do
    brew install "$__prog"
  done
fi
