#!/bin/bash

_command="$(basename "$0")"

if test "$_command" = "dockerize"; then
  if test -z "$1"; then
    echo "Usage: $_command <binary-name-to-shim>"
    echo
    echo "Build a shim command that run original command."
    echo "If the original command is not available, try docker version"
    exit 1
  fi

  _dockerfile="$(dirname "$(dirname "$0")")/docker/$1/Dockerfile.run"
  if test -f "$_dockerfile"; then
    docker build -t "$1" - < "$_dockerfile"
  else
    echo "No Dockerfile found for $1"
    exit 1
  fi

  if ! test -d "$HOME/.shims"; then
    mkdir -p "$HOME/.shims"
  fi
  ln -fs "$0" "$HOME/.shims/$1"
  exit 0
fi

if test -n "${commands[$_command]}" || test -z "$(docker images -q "$_command")"; then
  ${commands[$_command]} "$@"
  exit $?
fi

if tty -s; then
  docker run -it --rm -w "/etc/data" -v "$(pwd):/etc/data" "$_command" "$@"
else
  docker run -i --rm -w "/etc/data" -v "$(pwd):/etc/data" "$_command" "$@"
fi
