#!/bin/zsh

current=$(git rev-parse --abbrev-ref HEAD)
git fetch --all --prune
for branch in $(git branch --format "%(refname:short)");
do
  git checkout $branch;
  git pull --rebase --autostash
done
git checkout $current
