#!/bin/bash

PORT="$1"

if test -z "$PORT"; then
  echo "usage: $(basename "$0") [tcp:/udp:]<port>"
  echo "  check process occupied the given port"
  exit 1
fi

is_number() {
  case $1 in
    ''|*[!0-9]*) return 1 ;;
    *) return 0 ;;
  esac
}

if is_number "$PORT"; then
  PORT="tcp:$PORT"
fi

lsof -i "$PORT"
