#!/bin/bash

usage() {
  echo "USAGE"
  echo "  prcm [flags] <pr number>"
  echo
  echo "FLAGS"
  echo "  -h, --help              Show this message"
  echo "  -R, --repo=<OWNER/REPO> Select another repository using the OWNER/REPO format"
  echo
  echo "QUERY"
  echo "  If a repo flag is passed, it will take priority over auto-detect one."
}

_cat() {
  printf "%b" "$@" | sed 's/^"//g' | sed 's/"$//g' | bat -l md --paging never --color always --style changes
  return
}

_diff() {
  local filename="$1"
  shift
  printf "%b" "$@" | sed 's/^"//g' | sed 's/"$//g' | bat --file-name $filename --paging never --color always --style changes,header
  return
}

main() {
  local repo=""
  local debug=0
  while test "$1" != ""; do
    local PARAM=`echo $1 | sed 's/=.*//g'`
    local VALUE=`echo $1 | sed 's/^[^=]*=//g'`
    local EQUAL_SIGN=`echo $1 | sed 's/[^=]//g'`
    case $PARAM in
      -h | --help)
        usage
        return
        ;;
      --internal)
        if test -z "$EQUAL_SIGN"; then
          return 1
        fi
        shift
        if test "$VALUE" = "diff"; then
          local ARG="$1"
          shift
          "_$VALUE" "$ARG" "$(echo $@)"
        else
          "_$VALUE" "$(echo $@)"
        fi
        return
        ;;
      -R | --repo)
        if test -z "$EQUAL_SIGN"; then
          echo "ERROR: a repository is required (perhaps missing an equal sign?)"
          return 1
        fi
        repo="$VALUE"
        ;;
      --debug)
        debug=1
        ;;
      -*)
        echo "ERROR: unknown flag \"$1\""
        return 1
        ;;
      *)
        break
        ;;
    esac

    shift
  done

  local number="$@"
  if test -z "$number"; then
    echo 'PR number is required'
    return 1
  fi

  local repoOwner=""
  local repoName=""
  if test "$repo" = ""; then
    source _git_helper
    repoOwner=$(get_repo_owner)
    repoName=$(get_repo_name)
  else
    repoOwner=$(echo $repo | cut -d'/' -f1)
    repoName=$(echo $repo | cut -d'/' -f2)
  fi
  if test "$repoOwner" = "" -o "$repoName" = ""; then
    echo "ERROR: Both repository owner name repository name is required (perhaps it is not in the \"owner/repo\" format?)"
    return 1
  fi

  if test $debug -eq 1; then
    echo "#$number in $repoOwner/$repoName"
    return
  fi
  local graphQuery=$(cat ~/.dots/binaries/_ticket_comment.graphql)
  local response=$(gh api graphql -F limit="50" -F owner="$repoOwner" -F name="$repoName" -F number="$number" -f query="$graphQuery")
  if [ $? -ne 0 ]; then
    return 1
  fi

  echo "$response" | NUMBER="$number" gomplate -f ~/.dots/binaries/_timeline_item.tmpl --plugin tkcm="$HOME/.dots/binaries/tkcm" -d 'number=env:///NUMBER' -d 'response=stdin:///in.json'
  return
}

main $@
