#!/bin/sh

if test -n "$(command -v brew)"; then
  brew update
  brew upgrade
  brew cleanup
fi

if test -n "$(command -v zi)"; then
  zi update
fi

if test -n "$(command -v asdf)"; then
  asdf plugin update --all
fi

if test -n "$(command -v nvim)"; then
  nvim -c 'autocmd User LazyVimStarted lua=require("lazy").sync()' -c 'autocmd User LazySync qa!'
fi
