#!/bin/bash

if test "${BASH_SOURCE[0]}" = "$0"; then
  echo "ERROR: This command must be sourced"
  echo "It can be setup as an alias like this:"
  echo "  alias $(basename "$0")=\". $(basename "$0")\""
  exit 1
fi

if test -z "$WORKSPACE"; then
  if test -d "$HOME/Documents"; then
    WORKSPACE="$HOME/Documents"
  else
    echo "ERROR: WORKSPACE is not set"
    return 1
  fi
fi
query=""
if test "$1" = "-"; then
  cd "$WORKSPACE" || exit
  return
elif test -n "$@"; then
  query="-q $*"
fi
cd "$(find "$WORKSPACE" -mindepth 1 -maxdepth 3 -type d -name '.git' | rev | cut -d'/' -f2- | rev | fzf --height=20 '--preview=git -C {} branch' '--bind=ctrl-/:toggle-preview' "$query")" || exit
