FROM debian:buster-slim AS builder
RUN apt update
RUN apt install -y curl gcc libssl-dev pkg-config
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
RUN $HOME/.cargo/bin/cargo install starship --root /usr/local

FROM debian:buster-slim
WORKDIR /root
RUN apt update
RUN apt install -y libssl-dev
COPY --from=builder /usr/local/bin/starship /usr/bin/starship
CMD starship
