FROM alpine AS builder
RUN apk add --no-cache cargo libressl-dev pkgconfig
# starship v0.46 require a recent version of rust (probably 1.45)
# at the time of writing, lates rust version: 1.44
RUN cargo install starship --version ~0.45 --root /usr/local

FROM alpine
WORKDIR /root
RUN apk add --no-cache libressl-dev libgcc
COPY --from=builder /usr/local/bin/starship /usr/bin/starship
CMD starship
