add_newline = false

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$status\
$character
"""

right_format = """
$cmd_duration\
$username\
$hostname
"""

[cmd_duration]
format = "[$duration]($style) "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
truncate_to_repo = false

[hostname]
format = "[$hostname]($style)"

[username]
format = "[$user]($style)@"
disabled = true

[git_status]
conflicted = "[=](red)"
ahead = "[⇡](purple)"
behind = "[⇣](purple)"
diverged = "[⇕](purple)"
untracked = "[?](blue)"
stashed = "[\\$](purple)"
modified = "[!](yellow)"
staged = "[+](yellow)"
renamed = "[»](yellow)"
deleted = "[✘](red)"
ignore_submodules = true

[line_break]
disabled = true

[aws]
disabled =true

[battery]
disabled = true

[cmake]
disabled = true

[conda]
disabled =true

[crystal]
disabled =true

[dart]
disabled =true

[docker_context]
disabled =true

[dotnet]
disabled =true

[elixir]
disabled =true

[elm]
disabled =true

[env_var]
disabled =true

[erlang]
disabled =true

[gcloud]
disabled =true

[golang]
disabled =true

[helm]
disabled =true

[java]
disabled =true

[jobs]
disabled =true

[julia]
disabled =true

[kotlin]
disabled =true

[lua]
disabled =true

[hg_branch]
disabled =true

[nim]
disabled =true

[nix_shell]
disabled =true

[nodejs]
disabled =true

[ocaml]
disabled =true

[openstack]
disabled =true

[package]
disabled =true

[perl]
disabled =true

[php]
disabled =true

[purescript]
disabled =true

[python]
disabled =true

[ruby]
disabled =true

[rust]
disabled =true

[shlvl]
disabled =true

[singularity]
disabled =true

[swift]
disabled =true

[terraform]
disabled =true

[zig]
disabled =true
