name: Installation Test (via Docker)
on: push

# Available runners
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
jobs:
  local:
    name: Installation on ${{ matrix.os }} [${{ matrix.flag }}]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['debian:bullseye-slim', 'ubuntu:rolling']
        flag: [-v, '', -q]
    steps:
      - uses: actions/checkout@v4
      - name: Installation Info
        env:
          IMAGE: ${{ matrix.os }}
        run: |
          docker run -v $(pwd):/root/dots $IMAGE sh /root/dots/install.sh -i
      - name: Perform Installation
        env:
          IMAGE: ${{ matrix.os }}
          FLAG: ${{ matrix.flag }}
          REPO_NAME: spywhere/dotfiles
          REPO_BRANCH: installer
        run: |
          docker run -v $(pwd):/root/dots -e REPO_NAME=$REPO_NAME -e REPO_BRANCH=$REPO_BRANCH $IMAGE sh /root/dots/install.sh -y $FLAG
