name: Shell Check
on: push

jobs:
  shellcheck:
    name: Shell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1090 -e SC2034 -e SC2154 -e SC2317
        with:
          ignore: zsh
      - name: Ban echo
        run: |
          ! grep 'echo' install.sh
